### ISSUE TITLE
Doesn't allow multi-action stages

### ISSUE THREAD

**Issue by n8gard** [JamesWoolfenden/terraform-aws-codepipeline#3]
Hi. Came across your module while doing some searching. Gave it a quick look. Does not seem to be a clear way to have a pipeline Stage with multiple Action blocks. Do you know that this is not possible with `dynamic` stages or is it merely something you didn't solution?

**Comment by JamesWoolfenden** [comment]
It wasnt required for what i was working on. im sure it could support it, next time im having to use codepipeline ill update the module.
